In [39]:
import safety_gymnasium
from tqdm import tqdm, trange
import hashlib

In [40]:
def simulation(env, iter_nr = 1000, reward_free = False):
    obs, info = env.reset()
    # Set seeds
    # obs, _ = env.reset(seed=0)
    terminated, truncated = False, False
    ep_ret, ep_cost = 0, 0
    
    for _ in trange(iter_nr):
        assert env.observation_space.contains(obs)
        act = env.action_space.sample()
        assert env.action_space.contains(act)
        obs, reward, cost, terminated, truncated, info = env.step(act)
        # Only add the reward during deployment i.e. not reward-free
        if not reward_free:
            ep_ret += reward
        ep_cost += cost
        if terminated or truncated:
            observation, info = env.reset()

    env.close()
    return ep_ret, ep_cost

In [53]:
env = safety_gymnasium.make('SafetyPointGoal2-v0', render_mode='human', max_episode_steps = 1000)
# environment.reset()
# ret, cost = simulation(environment, reward_free = True)
# ret, cost

In [55]:
for i in dir(env.task):
    print(i)

__abstractmethods__
__class__
__delattr__
__dict__
__dir__
__doc__
__eq__
__format__
__ge__
__getattribute__
__gt__
__hash__
__init__
__init_subclass__
__le__
__lt__
__module__
__ne__
__new__
__reduce__
__reduce_ex__
__repr__
__setattr__
__sizeof__
__slots__
__str__
__subclasshook__
__weakref__
_abc_impl
_add_free_geoms
_add_geoms
_add_mocaps
_build
_build_agent
_build_placements_dict
_build_static_geoms_config
_build_world_config
_ego_xy
_free_geoms
_geoms
_get_viewer
_is_load_static_geoms
_mocaps
_obs_compass
_obs_lidar
_obs_lidar_natural
_obs_lidar_pseudo
_obs_vision
_obstacles
_parse
_placements_dict_from_object
_render_area
_render_compass
_render_lidar
_render_sphere
_set_goal
_update_viewer
_viewers
action_noise
action_space
agent
agent_name
build_goal_position
build_observation_space
build_staged_goal_position
calculate_cost
calculate_reward
compass_conf
cost_conf
data
debug
dist_goal
dist_staged_goal
floor_conf
goal
goal_achieved
hazards
last_dist_goal
lidar_conf
mechanism_con

In [51]:
env.task.goal = None  # Remove goal
env.task.dist_goal = None  # Remove goal distance tracking
# env.task.goal_achieved = False  # Ensure goal completion condition is ignored

In [66]:
env.reset()

(array([ 0.        ,  0.        ,  9.81      ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        , -0.37667889,
         0.32880543,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.46168267,  0.38140332,
         0.18898117,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.39706523,  0.50481054,  0.66362125,  0.71285392,  0.6022672 ,
         0.79885523,  0.61481301,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.30132379,  0.49911936,
         0.32699311,  0.18191966,  0.71105964,  0.7940205 ,  0.11066172]),
 {})

In [75]:
dir(env.task.agent)

['__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__slots__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_build_action_space',
 '_init_body_info',
 '_init_jnt_sensors',
 '_load_model',
 'action_space',
 'apply_action',
 'base',
 'body_info',
 'build_sensor_observation_space',
 'com',
 'debug',
 'debug_info',
 'dist_xy',
 'engine',
 'get_sensor',
 'is_alive',
 'keepout',
 'keyboard_control_callback',
 'locations',
 'mat',
 'obs_sensor',
 'placements',
 'pos',
 'random_generator',
 'reset',
 'rot',
 'sensor_conf',
 'sensor_info',
 'set_engine',
 'vel',
 'world_xy',
 'z_height']

In [76]:
env.task.num_steps

1000

In [ ]:
s, _ = env.reset()
for i in range(1000):
    act = env.action_space.sample()
    env.step(act)
    ns, _, _, terminated, truncated, _ = env.step(act)
    if terminated:
        print (f"Terminated in iter {i + 1}")
        if s == ns:
            print("States are the same bruh")
    if truncated:
        print (f"Truncated in iter {i + 1}")
    s = ns
    print("One step done")

Truncated in iter 500


AssertionError: Environment must be reset before stepping.

In [81]:
s

array([0.        , 0.        , 9.81      , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.49973329,
       0.01632916, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.20557594, 0.53956877, 0.33399283,
       0.        , 0.        , 0.        , 0.63889349, 0.71901521,
       0.10300368, 0.46701257, 0.39196807, 0.43011249, 0.47528243,
       0.56379898, 0.08851655, 0.18709485, 0.50941531, 0.32232046,
       0.01725441, 0.27526152, 0.76228501, 0.69628043, 0.20391412,
       0.63579955, 0.6087739 , 0.09102056, 0.50004599, 0.56711921,
       0.20920539, 0.34230943, 0.79591073, 0.4536013 , 0.72291357,
       0.65376539, 0.        , 0.21404971, 0.55550223, 0.53404657])

In [82]:
ns

array([ 2.68898589,  2.28094486,  9.81      ,  0.11105991,  0.01579968,
        0.        , -0.        ,  0.        , -0.79487563,  0.49911525,
        0.02973161,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.17087594,  0.53929468,  0.36841874,
        0.        ,  0.        ,  0.        ,  0.58915459,  0.71979689,
        0.1306423 ,  0.46721905,  0.42580416,  0.42977952,  0.434887  ,
        0.56310377,  0.12821677,  0.15370026,  0.5088759 ,  0.35517565,
        0.        ,  0.27479303,  0.76293766,  0.74515793,  0.22223876,
        0.61809754,  0.63647606,  0.05480677,  0.49994576,  0.56684986,
        0.25036811,  0.28784383,  0.79510634,  0.50726251,  0.72244043,
        0.69838603,  0.        ,  0.18836053,  0.54110128,  0.55616385])

In [ ]:
for _ in range(100):
    act = env.action_space.sample()
    new_state, reward, cost, terminated, truncated, info = env.step(act)

In [23]:
reward

-0.0033912437081586866

In [29]:
new_state

array([ 3.33099610e+00,  6.60883549e+00,  1.44367428e+01,  1.84440792e-02,
       -7.61994594e-02,  1.01142211e-02,  1.01282470e-01,  6.29291039e-01,
       -6.88697815e-01, -1.43894203e-01, -4.78830075e-01,  4.02707896e-03,
        8.05895484e-01, -1.63789522e+00,  6.36175930e-01,  7.51492993e-01,
       -5.50383262e-01,  3.63780903e-01,  4.90767097e-01,  8.34865644e-01,
        2.49293026e-01, -4.40914887e-01, -8.81026442e-03,  8.97505678e-01,
        1.43707622e-01,  2.02642017e-01,  5.89343947e-02,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        5.64273398e-01,  5.26614584e-01,  3.98543005e-01,  4.18327333e-01,
        1.52471030e-01,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  5.75992975e-01,  7.74824509e-01,  1.98831534e-01,
        5.49742919e-01,  

In [2]:
import torch
if torch.cuda.is_available():
    dev = "cuda:0"
else:
    dev = "cpu"

In [3]:
dev

'cuda:0'